swagger: '2.0'
paths:
  {url}/role/index:
    get:
      tags:
      - Rbac role
      summary: 角色列表
      operationId: index
      parameters:
      - in: formData
        name: token
        type: string
        description: 用户TOKEN
        required: true
      responses:
        200:
          description: 操作成功

  {url}/role/show:
    get:
      tags:
      - Rbac role
      summary: 角色详情
      operationId: show
      parameters:
      - in: formData
        name: token
        type: string
        description: 用户TOKEN
        required: true
      - in: formData
        name: id
        type: integer
        description: 角色Id
        required: true
      responses:
        200:
          description: 操作成功

  {url}/role/create:
    post:
      tags:
      - Rbac role
      summary: 创建角色
      operationId: create
      parameters:
      - in: formData
        name: token
        type: string
        description: 用户TOKEN
        required: true
      - in: formData
        name: name
        type: string
        description: 角色名称
        required: true
      - in: formData
        name: permission_ids
        type: string
        description: 权限Id,用逗号(,)分割
        required: true
      responses:
        200:
          description: 操作成功

  {url}/role/delete:
    post:
      tags:
      - Rbac role
      summary: 删除权限
      operationId: destory
      parameters:
      - in: formData
        name: token
        type: string
        description: 用户TOKEN
        required: true
      - in: formData
        name: id
        type: integer
        description: 角色Id
        required: true
      responses:
        200:
          description: 操作成功

  {url}/role/edit:
    post:
      tags:
      - Rbac role
      summary: 编辑角色
      operationId: edit
      parameters:
      - in: formData
        name: token
        type: string
        description: 用户TOKEN
        required: true
      - in: formData
        name: id
        type: integer
        description: 角色Id
        required: true
      - in: formData
        name: name
        type: string
        description: 角色名称
        required: true
      - in: formData
        name: permission_ids
        type: string
        description: 权限Id,用逗号(,)分割
        required: true
      responses:
        200:
          description: 操作成功

  {url}/role/allrole:
    get:
      tags:
      - Rbac role
      summary: 获取所有角色
      operationId: getAllRole
      parameters:
      - in: formData
        name: token
        type: string
        description: 用户TOKEN
        required: true
      responses:
        200:
          description: 操作成功

  {url}/role/getPermissionByRole:
    get:
      tags:
      - Rbac role
      summary: 通过角色获取权限
      operationId: getPermissionByRole
      parameters:
      - in: formData
        name: token
        type: string
        description: 用户TOKEN
        required: true
      - in: formData
        name: role_ids
        type: string
        description: 角色Id(多个角色用逗号(,)分割)
        required: true
      responses:
        200:
          description: 操作成功